spring:
  datasource:
    url: jdbc:mysql://localhost:3306/companycalendar
    username: root
    password: root1234

  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop

mailing:
  mailgun:
    apiKey: "e8a3dc9116e2125fe4a60343949cd8cb-52b6835e-6956cbed"
    mailSenderUrl: "https://api.mailgun.net/v3/sandbox5f1b6d9b5e9e4eaa90068f472ead00db.mailgun.org/messages"
  mailFrom: "Mailgun Sandbox <postmaster@sandbox5f1b6d9b5e9e4eaa90068f472ead00db.mailgun.org>"
  messageTemplate: "Hello %s, Ã©rtekezleted van %s - %s a %s teremben."

# mailgun: apiKey, mailSenderUrl, mailFrom

